---
driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  # use_sudo: false

transport:
  name: dokken

provisioner:
  name: dokken
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7
    driver:
      #image: dokken/centos-7
      platform: rhel
      pid_one_command: /usr/lib/systemd/systemd
      #platform: rhel
      #run_command: /usr/lib/systemd/systemd

suites:
  - name: default
    run_list:
      - recipe[gm_dev_server::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
